package com.preventia.appointment.dto;

import java.time.OffsetDateTime;

/**
 * Inbound request payload for scheduling a new appointment.
 *
 * Daily.co room URL and name are no longer supplied by the caller —
 * they are auto-generated by DailyRoomService on the backend.
 *
 * sponsorId / sponsorName are optional — present when an NRI child
 * sponsors or observes the session remotely.
 */
public record CreateAppointmentRequest(
        Long            recipientId,
        String          recipientName,

        Long            sponsorId,       // nullable
        String          sponsorName,     // nullable

        Long            doctorId,
        String          doctorName,

        OffsetDateTime  startTime,
        OffsetDateTime  endTime
) {}
